### ISSUE TITLE
Add Clock/Preset symbol to represent a device is running on a schedule or preset.

### ISSUE THREAD

**Issue by bansaldhruv1** [vikilabs-code/hombot-issues#204] opened 2016-05-09 09:23 UTC

**Comment by artakshar** [comment] 2016-05-09 13:41
@bansaldhruv1 Please refer to #210 I have solved this issue and seems like #210 is duplicate of this. Please close this if you've reviewed #210. Thanks!

**Closed** 2016-05-10 09:09 UTC
Labels: design, Dhruv, enhancement
